// generated by ast_gen.py -- do not edit
#include "parse.h"

const char* NodeKindName(NodeKind k) {
  // kNodeNameTable[NodeKind] => const char* name
  static const char* const kNodeNameTable[NodeKind_MAX+2] = {
"Bad", "Field", "Pkg", "File", "Comment", "Nil", "BoolLit", "IntLit",
    "FloatLit", "StrLit", "Id", "BinOp", "PrefixOp", "PostfixOp", "Return",
    "Assign", "Tuple", "Array", "Block", "Fun", "Call", "Template",
    "TemplateInstance", "TypeCast", "Const", "Var", "Param", "TemplateParam",
    "Ref", "NamedArg", "Selector", "Index", "Slice", "If", "TypeExpr",
    "TypeType", "IdType", "AliasType", "RefType", "BasicType", "ArrayType",
    "TupleType", "StructType", "FunType", "TemplateType", "TemplateParamType",
    "?"
  };
  return kNodeNameTable[MIN(NodeKind_MAX+1,k)];
}

const u8 kNodeStructSizeTab[46] = {
  sizeof(struct BadNode),
  sizeof(struct FieldNode),
  sizeof(struct PkgNode),
  sizeof(struct FileNode),
  sizeof(struct CommentNode),
  sizeof(struct NilNode),
  sizeof(struct BoolLitNode),
  sizeof(struct IntLitNode),
  sizeof(struct FloatLitNode),
  sizeof(struct StrLitNode),
  sizeof(struct IdNode),
  sizeof(struct BinOpNode),
  sizeof(struct PrefixOpNode),
  sizeof(struct PostfixOpNode),
  sizeof(struct ReturnNode),
  sizeof(struct AssignNode),
  sizeof(struct TupleNode),
  sizeof(struct ArrayNode),
  sizeof(struct BlockNode),
  sizeof(struct FunNode),
  sizeof(struct CallNode),
  sizeof(struct TemplateNode),
  sizeof(struct TemplateInstanceNode),
  sizeof(struct TypeCastNode),
  sizeof(struct ConstNode),
  sizeof(struct VarNode),
  sizeof(struct ParamNode),
  sizeof(struct TemplateParamNode),
  sizeof(struct RefNode),
  sizeof(struct NamedArgNode),
  sizeof(struct SelectorNode),
  sizeof(struct IndexNode),
  sizeof(struct SliceNode),
  sizeof(struct IfNode),
  sizeof(struct TypeExprNode),
  sizeof(struct TypeTypeNode),
  sizeof(struct IdTypeNode),
  sizeof(struct AliasTypeNode),
  sizeof(struct RefTypeNode),
  sizeof(struct BasicTypeNode),
  sizeof(struct ArrayTypeNode),
  sizeof(struct TupleTypeNode),
  sizeof(struct StructTypeNode),
  sizeof(struct FunTypeNode),
  sizeof(struct TemplateTypeNode),
  sizeof(struct TemplateParamTypeNode),
};
